/* The 38 far entries point into the adjacent DGROUP error-text bytes. The
 * table is a separate contribution; those strings remain unclaimed raw data. */
extern char __based(__segname("DGROUP")) _ctype_[];

char far * __based(__segname("DGROUP")) sys_errlist[38] = {
    (char far *)(_ctype_ + 262),
    (char far *)(_ctype_ + 270),
    (char far *)(_ctype_ + 271),
    (char far *)(_ctype_ + 297),
    (char far *)(_ctype_ + 298),
    (char far *)(_ctype_ + 299),
    (char far *)(_ctype_ + 300),
    (char far *)(_ctype_ + 301),
    (char far *)(_ctype_ + 319),
    (char far *)(_ctype_ + 337),
    (char far *)(_ctype_ + 353),
    (char far *)(_ctype_ + 354),
    (char far *)(_ctype_ + 355),
    (char far *)(_ctype_ + 371),
    (char far *)(_ctype_ + 389),
    (char far *)(_ctype_ + 390),
    (char far *)(_ctype_ + 391),
    (char far *)(_ctype_ + 392),
    (char far *)(_ctype_ + 404),
    (char far *)(_ctype_ + 422),
    (char far *)(_ctype_ + 423),
    (char far *)(_ctype_ + 424),
    (char far *)(_ctype_ + 425),
    (char far *)(_ctype_ + 442),
    (char far *)(_ctype_ + 443),
    (char far *)(_ctype_ + 463),
    (char far *)(_ctype_ + 464),
    (char far *)(_ctype_ + 465),
    (char far *)(_ctype_ + 466),
    (char far *)(_ctype_ + 490),
    (char far *)(_ctype_ + 491),
    (char far *)(_ctype_ + 492),
    (char far *)(_ctype_ + 493),
    (char far *)(_ctype_ + 494),
    (char far *)(_ctype_ + 508),
    (char far *)(_ctype_ + 525),
    (char far *)(_ctype_ + 526),
    (char far *)(_ctype_ + 556)
};
