; Faithful MASM instruction reconstruction of _DoInt3.
.186
SIMTWO_MODULE SEGMENT BYTE PUBLIC 'CODE'
ASSUME CS:SIMTWO_MODULE
PUBLIC _DoInt3
_DoInt3 PROC NEAR
    int 3
_DoInt3 ENDP
SIMTWO_MODULE ENDS
END
