/* Draw the sixteen-segment outline for the selected body orientation.
 * L/D tables provide signed per-phase offsets; the second pass uses phase
 * rotated by four steps.  The four current-point anchors are the editor
 * scratch words consumed by ed_LineTo. */
extern int far ConvColor(int color);
extern void far GSetAttrib(int foreColor, int backColor, int pattern);
extern void far ed_LineTo(int x, int y);
extern int far editBufInvalidFlag[];
extern int near edata[];
extern char far Lx[];
extern char far Ly[];
extern char far Dx[];
extern char far Dy[];
extern char far L1xA[];
extern char far L1xB[];
extern char far L1yA[];
extern char far L1yB[];
extern char far L2xA[];
extern char far L2xB[];
extern char far L2yA[];
extern char far L2yB[];
extern char far L3xA[];
extern char far L3xB[];
extern char far L3yA[];
extern char far L3yB[];
extern char far L4xA[];
extern char far L4xB[];
extern char far L4yA[];
extern char far L4yB[];
extern char far D1xA[];
extern char far D1xB[];
extern char far D1yA[];
extern char far D1yB[];
extern char far D2xA[];
extern char far D2xB[];
extern char far D2yA[];
extern char far D2yB[];
extern char far D3xA[];
extern char far D3xB[];
extern char far D3yA[];
extern char far D3yB[];
extern char far D4xA[];
extern char far D4xB[];
extern char far D4yA[];
extern char far D4yB[];

void far DrawLegs(register int x, register int y, int body, int phase)
{
    volatile int phaseIndex;
    int far * volatile penX;

    phaseIndex = ((char)phase - 0xfc) & 7;
    GSetAttrib(ConvColor(15), 0, 0);

    switch (body) {
    case 0:
        /* Orientation 0: use the L anchors. */
        penX = editBufInvalidFlag - 3;
        *penX = x + Lx[0];
        edata[57] = y + Ly[0];
        ed_LineTo(x + L1xA[phase], y + L1yA[phase]);
        ed_LineTo(x + L1xB[phase], y + L1yB[phase]);
        *penX = x + Lx[1];
        edata[57] = y + Ly[1];
        ed_LineTo(x + L2xA[phase], y + L2yA[phase]);
        ed_LineTo(x + L2xB[phase], y + L2yB[phase]);
        *penX = x + Lx[2];
        edata[57] = y + Ly[2];
        ed_LineTo(x + L3xA[phase], y + L3yA[phase]);
        ed_LineTo(x + L3xB[phase], y + L3yB[phase]);
        *penX = x + Lx[3];
        edata[57] = y + Ly[3];
        ed_LineTo(x + L4xA[phase], y + L4yA[phase]);
        ed_LineTo(x + L4xB[phase], y + L4yB[phase]);
        *penX = x + Lx[0];
        edata[57] = y + Ly[0];
        ed_LineTo(x - L1xA[phaseIndex], y + L1yA[phaseIndex]);
        ed_LineTo(x - L1xB[phaseIndex], y + L1yB[phaseIndex]);
        *penX = x + Lx[1];
        edata[57] = y + Ly[1];
        ed_LineTo(x - L2xA[phaseIndex], y + L2yA[phaseIndex]);
        ed_LineTo(x - L2xB[phaseIndex], y + L2yB[phaseIndex]);
        *penX = x + Lx[2];
        edata[57] = y + Ly[2];
        ed_LineTo(x - L3xA[phaseIndex], y + L3yA[phaseIndex]);
        ed_LineTo(x - L3xB[phaseIndex], y + L3yB[phaseIndex]);
        *penX = x + Lx[3];
        edata[57] = y + Ly[3];
        ed_LineTo(x - L4xA[phaseIndex], y + L4yA[phaseIndex]);
        x = x + L4yB[phaseIndex];
        y = y - L4xB[phaseIndex];
        break;
    case 1:
        /* Orientation 1: use the D anchors. */
        penX = editBufInvalidFlag - 3;
        *penX = x + Dx[0];
        edata[57] = y + Dy[0];
        ed_LineTo(x + D1xA[phase], y + D1yA[phase]);
        ed_LineTo(x + D1xB[phase], y + D1yB[phase]);
        *penX = x + Dx[1];
        edata[57] = y + Dy[1];
        ed_LineTo(x + D2xA[phase], y + D2yA[phase]);
        ed_LineTo(x + D2xB[phase], y + D2yB[phase]);
        *penX = x + Dx[2];
        edata[57] = y + Dy[2];
        ed_LineTo(x + D3xA[phase], y + D3yA[phase]);
        ed_LineTo(x + D3xB[phase], y + D3yB[phase]);
        *penX = x + Dx[3];
        edata[57] = y + Dy[3];
        ed_LineTo(x + D4xA[phase], y + D4yA[phase]);
        ed_LineTo(x + D4xB[phase], y + D4yB[phase]);
        *penX = x + Dx[0];
        edata[57] = y + Dy[0];
        ed_LineTo(x - D1yA[phaseIndex], y - D1xA[phaseIndex]);
        ed_LineTo(x - D1yB[phaseIndex], y - D1xB[phaseIndex]);
        *penX = x + Dx[1];
        edata[57] = y + Dy[1];
        ed_LineTo(x - D2yA[phaseIndex], y - D2xA[phaseIndex]);
        ed_LineTo(x - D2yB[phaseIndex], y - D2xB[phaseIndex]);
        *penX = x + Dx[2];
        edata[57] = y + Dy[2];
        ed_LineTo(x - D3yA[phaseIndex], y - D3xA[phaseIndex]);
        ed_LineTo(x - D3yB[phaseIndex], y - D3xB[phaseIndex]);
        *penX = x + Dx[3];
        edata[57] = y + Dy[3];
        ed_LineTo(x - D4yA[phaseIndex], y - D4xA[phaseIndex]);
        x = x - D4xB[phaseIndex];
        y = y - D4yB[phaseIndex];
        break;
    case 2:
        /* Orientation 2: use the L anchors. */
        penX = editBufInvalidFlag - 3;
        *penX = x - Ly[0];
        edata[57] = y + Lx[0];
        ed_LineTo(x - L1yA[phase], y + L1xA[phase]);
        ed_LineTo(x - L1yB[phase], y + L1xB[phase]);
        *penX = x - Ly[1];
        edata[57] = y + Lx[1];
        ed_LineTo(x - L2yA[phase], y + L2xA[phase]);
        ed_LineTo(x - L2yB[phase], y + L2xB[phase]);
        *penX = x - Ly[2];
        edata[57] = y + Lx[2];
        ed_LineTo(x - L3yA[phase], y + L3xA[phase]);
        ed_LineTo(x - L3yB[phase], y + L3xB[phase]);
        *penX = x - Ly[3];
        edata[57] = y + Lx[3];
        ed_LineTo(x - L4yA[phase], y + L4xA[phase]);
        ed_LineTo(x - L4yB[phase], y + L4xB[phase]);
        *penX = x - Ly[0];
        edata[57] = y + Lx[0];
        ed_LineTo(x - L1yA[phaseIndex], y - L1xA[phaseIndex]);
        ed_LineTo(x - L1yB[phaseIndex], y - L1xB[phaseIndex]);
        *penX = x - Ly[1];
        edata[57] = y + Lx[1];
        ed_LineTo(x - L2yA[phaseIndex], y - L2xA[phaseIndex]);
        ed_LineTo(x - L2yB[phaseIndex], y - L2xB[phaseIndex]);
        *penX = x - Ly[2];
        edata[57] = y + Lx[2];
        ed_LineTo(x - L3yA[phaseIndex], y - L3xA[phaseIndex]);
        ed_LineTo(x - L3yB[phaseIndex], y - L3xB[phaseIndex]);
        *penX = x - Ly[3];
        edata[57] = y + Lx[3];
        ed_LineTo(x - L4yA[phaseIndex], y - L4xA[phaseIndex]);
        x = x - L4xB[phaseIndex];
        y = y - L4yB[phaseIndex];
        break;
    case 3:
        /* Orientation 3: use the D anchors. */
        penX = editBufInvalidFlag - 3;
        *penX = x + Dx[0];
        edata[57] = y - Dy[0];
        ed_LineTo(x + D1xA[phase], y - D1yA[phase]);
        ed_LineTo(x + D1xB[phase], y - D1yB[phase]);
        *penX = x + Dx[1];
        edata[57] = y - Dy[1];
        ed_LineTo(x + D2xA[phase], y - D2yA[phase]);
        ed_LineTo(x + D2xB[phase], y - D2yB[phase]);
        *penX = x + Dx[2];
        edata[57] = y - Dy[2];
        ed_LineTo(x + D3xA[phase], y - D3yA[phase]);
        ed_LineTo(x + D3xB[phase], y - D3yB[phase]);
        *penX = x + Dx[3];
        edata[57] = y - Dy[3];
        ed_LineTo(x + D4xA[phase], y - D4yA[phase]);
        ed_LineTo(x + D4xB[phase], y - D4yB[phase]);
        *penX = x + Dx[0];
        edata[57] = y - Dy[0];
        ed_LineTo(x - D1yA[phaseIndex], y + D1xA[phaseIndex]);
        ed_LineTo(x - D1yB[phaseIndex], y + D1xB[phaseIndex]);
        *penX = x + Dx[1];
        edata[57] = y - Dy[1];
        ed_LineTo(x - D2yA[phaseIndex], y + D2xA[phaseIndex]);
        ed_LineTo(x - D2yB[phaseIndex], y + D2xB[phaseIndex]);
        *penX = x + Dx[2];
        edata[57] = y - Dy[2];
        ed_LineTo(x - D3yA[phaseIndex], y + D3xA[phaseIndex]);
        ed_LineTo(x - D3yB[phaseIndex], y + D3xB[phaseIndex]);
        *penX = x + Dx[3];
        edata[57] = y - Dy[3];
        ed_LineTo(x - D4yA[phaseIndex], y + D4xA[phaseIndex]);
        x = x + D4xB[phaseIndex];
        y = y - D4yB[phaseIndex];
        break;
    case 4:
        /* Orientation 4: use the L anchors. */
        penX = editBufInvalidFlag - 3;
        *penX = x - Lx[0];
        edata[57] = y - Ly[0];
        ed_LineTo(x - L1xA[phase], y - L1yA[phase]);
        ed_LineTo(x - L1xB[phase], y - L1yB[phase]);
        *penX = x - Lx[1];
        edata[57] = y - Ly[1];
        ed_LineTo(x - L2xA[phase], y - L2yA[phase]);
        ed_LineTo(x - L2xB[phase], y - L2yB[phase]);
        *penX = x - Lx[2];
        edata[57] = y - Ly[2];
        ed_LineTo(x - L3xA[phase], y - L3yA[phase]);
        ed_LineTo(x - L3xB[phase], y - L3yB[phase]);
        *penX = x - Lx[3];
        edata[57] = y - Ly[3];
        ed_LineTo(x - L4xA[phase], y - L4yA[phase]);
        ed_LineTo(x - L4xB[phase], y - L4yB[phase]);
        *penX = x - Lx[0];
        edata[57] = y - Ly[0];
        ed_LineTo(x + L1xA[phaseIndex], y - L1yA[phaseIndex]);
        ed_LineTo(x + L1xB[phaseIndex], y - L1yB[phaseIndex]);
        *penX = x - Lx[1];
        edata[57] = y - Ly[1];
        ed_LineTo(x + L2xA[phaseIndex], y - L2yA[phaseIndex]);
        ed_LineTo(x + L2xB[phaseIndex], y - L2yB[phaseIndex]);
        *penX = x - Lx[2];
        edata[57] = y - Ly[2];
        ed_LineTo(x + L3xA[phaseIndex], y - L3yA[phaseIndex]);
        ed_LineTo(x + L3xB[phaseIndex], y - L3yB[phaseIndex]);
        *penX = x - Lx[3];
        edata[57] = y - Ly[3];
        x = x + L4yB[phaseIndex];
        y = y + L4xB[phaseIndex];
        ed_LineTo(x - L4yB[phaseIndex], y + L4xB[phaseIndex]);
        break;
    case 5:
        /* Orientation 5: use the D anchors. */
        penX = editBufInvalidFlag - 3;
        *penX = x - Dx[0];
        edata[57] = y - Dy[0];
        ed_LineTo(x - D1xA[phase], y - D1yA[phase]);
        ed_LineTo(x - D1xB[phase], y - D1yB[phase]);
        *penX = x - Dx[1];
        edata[57] = y - Dy[1];
        ed_LineTo(x - D2xA[phase], y - D2yA[phase]);
        ed_LineTo(x - D2xB[phase], y - D2yB[phase]);
        *penX = x - Dx[2];
        edata[57] = y - Dy[2];
        ed_LineTo(x - D3xA[phase], y - D3yA[phase]);
        ed_LineTo(x - D3xB[phase], y - D3yB[phase]);
        *penX = x - Dx[3];
        edata[57] = y - Dy[3];
        ed_LineTo(x - D4xA[phase], y - D4yA[phase]);
        ed_LineTo(x - D4xB[phase], y - D4yB[phase]);
        *penX = x - Dx[0];
        edata[57] = y - Dy[0];
        ed_LineTo(x + D1yA[phaseIndex], y + D1xA[phaseIndex]);
        ed_LineTo(x + D1yB[phaseIndex], y + D1xB[phaseIndex]);
        *penX = x - Dx[1];
        edata[57] = y - Dy[1];
        ed_LineTo(x + D2yA[phaseIndex], y + D2xA[phaseIndex]);
        ed_LineTo(x + D2yB[phaseIndex], y + D2xB[phaseIndex]);
        *penX = x - Dx[2];
        edata[57] = y - Dy[2];
        ed_LineTo(x + D3yA[phaseIndex], y + D3xA[phaseIndex]);
        ed_LineTo(x + D3yB[phaseIndex], y + D3xB[phaseIndex]);
        *penX = x - Dx[3];
        edata[57] = y - Dy[3];
        x = x + D4yB[phaseIndex];
        y = y + D4xB[phaseIndex];
        ed_LineTo(x + D4xB[phaseIndex], y + D4yB[phaseIndex]);
        break;
    case 6:
        /* Orientation 6: use the L anchors. */
        penX = editBufInvalidFlag - 3;
        *penX = x + Ly[0];
        edata[57] = y - Lx[0];
        ed_LineTo(x + L1yA[phase], y - L1xA[phase]);
        ed_LineTo(x + L1yB[phase], y - L1xB[phase]);
        *penX = x + Ly[1];
        edata[57] = y - Lx[1];
        ed_LineTo(x + L2yA[phase], y - L2xA[phase]);
        ed_LineTo(x + L2yB[phase], y - L2xB[phase]);
        *penX = x + Ly[2];
        edata[57] = y - Lx[2];
        ed_LineTo(x + L3yA[phase], y - L3xA[phase]);
        ed_LineTo(x + L3yB[phase], y - L3xB[phase]);
        *penX = x + Ly[3];
        edata[57] = y - Lx[3];
        ed_LineTo(x + L4yA[phase], y - L4xA[phase]);
        ed_LineTo(x + L4yB[phase], y - L4xB[phase]);
        *penX = x + Ly[0];
        edata[57] = y - Lx[0];
        ed_LineTo(x + L1yA[phaseIndex], y + L1xA[phaseIndex]);
        ed_LineTo(x + L1yB[phaseIndex], y + L1xB[phaseIndex]);
        *penX = x + Ly[1];
        edata[57] = y - Lx[1];
        ed_LineTo(x + L2yA[phaseIndex], y + L2xA[phaseIndex]);
        ed_LineTo(x + L2yB[phaseIndex], y + L2xB[phaseIndex]);
        *penX = x + Ly[2];
        edata[57] = y - Lx[2];
        ed_LineTo(x + L3yA[phaseIndex], y + L3xA[phaseIndex]);
        ed_LineTo(x + L3yB[phaseIndex], y + L3xB[phaseIndex]);
        *penX = x + Ly[3];
        edata[57] = y - Lx[3];
        x = x + L4xB[phaseIndex];
        y = y + L4yB[phaseIndex];
        ed_LineTo(x + L4xB[phaseIndex], y + L4yB[phaseIndex]);
        break;
    case 7:
        /* Orientation 7: use the D anchors. */
        penX = editBufInvalidFlag - 3;
        *penX = x - Dx[0];
        edata[57] = y + Dy[0];
        ed_LineTo(x - D1xA[phase], y + D1yA[phase]);
        ed_LineTo(x - D1xB[phase], y + D1yB[phase]);
        *penX = x - Dx[1];
        edata[57] = y + Dy[1];
        ed_LineTo(x - D2xA[phase], y + D2yA[phase]);
        ed_LineTo(x - D2xB[phase], y + D2yB[phase]);
        *penX = x - Dx[2];
        edata[57] = y + Dy[2];
        ed_LineTo(x - D3xA[phase], y + D3yA[phase]);
        ed_LineTo(x - D3xB[phase], y + D3yB[phase]);
        *penX = x - Dx[3];
        edata[57] = y + Dy[3];
        ed_LineTo(x - D4xA[phase], y + D4yA[phase]);
        ed_LineTo(x - D4xB[phase], y + D4yB[phase]);
        *penX = x - Dx[0];
        edata[57] = y + Dy[0];
        ed_LineTo(x + D1yA[phaseIndex], y - D1xA[phaseIndex]);
        ed_LineTo(x + D1yB[phaseIndex], y - D1xB[phaseIndex]);
        *penX = x - Dx[1];
        edata[57] = y + Dy[1];
        ed_LineTo(x + D2yA[phaseIndex], y - D2xA[phaseIndex]);
        ed_LineTo(x + D2yB[phaseIndex], y - D2xB[phaseIndex]);
        *penX = x - Dx[2];
        edata[57] = y + Dy[2];
        ed_LineTo(x + D3yA[phaseIndex], y - D3xA[phaseIndex]);
        ed_LineTo(x + D3yB[phaseIndex], y - D3xB[phaseIndex]);
        *penX = x - Dx[3];
        edata[57] = y + Dy[3];
        ed_LineTo(x + D4yA[phaseIndex], y - D4xA[phaseIndex]);
        x = x - D4xB[phaseIndex];
        y = y + D4yB[phaseIndex];
        break;
    }

    ed_LineTo(x, y);
}
